/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package firebase.cloudmessaging;

import static firebase.cloudmessaging.Utils.getApplicationContext;

import android.app.Activity;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.media.AudioAttributes;
import android.media.RingtoneManager;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;

import androidx.annotation.Nullable;
import androidx.preference.PreferenceManager;

import com.google.firebase.messaging.FirebaseMessaging;
import com.google.firebase.messaging.RemoteMessage;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;
import org.json.JSONObject;

import ti.modules.titanium.android.notificationmanager.NotificationChannelProxy;

@Kroll.module(name = "CloudMessaging", id = "firebase.cloudmessaging", propertyAccessors = {
    "notifyOnPushTap",
})
public class CloudMessagingModule extends KrollModule {

    static final String LCAT = "FirebaseCloudMessaging";
    private static final String FORCE_SHOW_IN_FOREGROUND = "titanium.firebase.cloudmessaging.key";
    private static CloudMessagingModule instance = null;
    private static String fcmToken = null;
    private String notificationData = "";

    public static final String LAST_MESSAGE_DATA_KEY_NAME = "titanium.firebase.cloudmessaging.message";

    // DO NOT MODIFY FIELD NAMES - EXPOSED TO BRAZE MODULE, if required, update field values only.
    public static final String FIREBASE_EVENT_DID_RECEIVE_MESSAGE = "triggerDidReceiveMessage";
    public static final String FIREBASE_EVENT_DID_OPEN_NOTIFICATION = "triggerDidOpenNotification";

    public CloudMessagingModule() {
        super("CloudMessaging");
        instance = this;

        // To keep parity with iOS Ti.Network.registerForPushNotifications's callback behaviour.
        defaultValues.put("notifyOnPushTap", true);
    }

    public static CloudMessagingModule getInstance() {
        return instance;
    }

    @Nullable
    private static Intent getCurrentIntent() {
        Activity activity = TiApplication.getAppRootOrCurrentActivity();
        if (activity == null) {
            return null;
        }

        return activity.getIntent();
    }


    // Keep primitives as-is so JS gets booleans/numbers; stringify anything else
    // (Parcelables etc.) so it can still cross the bridge.
    private static Object toDictValue(Object value) {
        if (value instanceof String || value instanceof Boolean || value instanceof Number) {
            return value;
        }
        return String.valueOf(value);
    }

    // clang-format off
    @Kroll.method
    @Kroll.getProperty
    private KrollDict getLastData()
    // clang-format on
    {
        KrollDict data = new KrollDict();

        try {
            Intent intent = getCurrentIntent();
            if (intent == null) {
                return data;
            }

            Bundle extras = intent.getExtras();

            if (extras != null) {
                for (String key : extras.keySet()) {
                    Object value = extras.get(key);
                    if (value instanceof Bundle bundle) {
                        for (String bundleKey : bundle.keySet()) {
                            Object bundleValue = bundle.get(bundleKey);
                            if (bundleValue != null) {
                                data.put(key + "_" + bundleKey, toDictValue(bundleValue));
                            }
                        }
                    } else if (value != null) {
                        data.put(key, toDictValue(value));
                    }
                }

                data.put("inBackground", true);
            } else {
                Log.d(LCAT, "Empty extras in Intent");
                if (!notificationData.isEmpty()) {
                    data = new KrollDict(new JSONObject(notificationData));
                    data.put("inBackground", true);
                }
            }

            if (data.get("message") == null) {
                SharedPreferences preferences =
                        PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
                String prefMessage = preferences.getString(LAST_MESSAGE_DATA_KEY_NAME, null);
                if (prefMessage != null) {
                    data.put("message", new KrollDict(new JSONObject(prefMessage)));
                }


                clearLastData();
            }
        } catch (Exception ex) {
            Log.e(LCAT, "getLastData" + ex);
        }

        return data;
    }

    // Methods
    @Kroll.method
    public void registerForPushNotifications() {
        if (Build.VERSION.SDK_INT >= 33) {
            if (getApplicationContext().checkSelfPermission("android.permission.POST_NOTIFICATIONS") == PackageManager.PERMISSION_GRANTED) {
                fireEvent("success", new KrollDict());
                getToken();
            } else {
                Log.w(LCAT, "POST_NOTIFICATIONS runtime permission is missing. Please request that permission first.");
            }
        } else {
            fireEvent("success", new KrollDict());
            getToken();
        }
        parseBootIntent();
    }

    @Kroll.method
    public void subscribeToTopic(String topic) {
        FirebaseMessaging.getInstance().subscribeToTopic(topic).addOnCompleteListener(task -> {
            KrollDict data = new KrollDict();
            data.put("success", task.isSuccessful());
            fireEvent("subscribe", data);
        });
        Log.d(LCAT, "subscribe to " + topic);
    }

    @Kroll.method
    public void unsubscribeFromTopic(String topic) {
        FirebaseMessaging.getInstance().unsubscribeFromTopic(topic).addOnCompleteListener(task -> {
            KrollDict data = new KrollDict();
            data.put("success", task.isSuccessful());
            fireEvent("unsubscribe", data);
        });
        Log.d(LCAT, "unsubscribe from " + topic);
    }

    @Kroll.method
    public void appDidReceiveMessage(KrollDict opt) {
        // empty
    }

    @Kroll.method
    public void clearLastData() {
        SharedPreferences preferences =
                PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
        preferences.edit().remove(LAST_MESSAGE_DATA_KEY_NAME).apply();

        // Remove data from intent as well.
        Intent intent = getCurrentIntent();
        if (intent != null) {
            intent.removeExtra("fcm_data");
        }
    }

    @Kroll.method
    public void getToken() {
        FirebaseMessaging fm = FirebaseMessaging.getInstance();
        fm.getToken().addOnCompleteListener(task -> {
            if (task.isSuccessful()) {
                KrollDict data = new KrollDict();
                fcmToken = task.getResult();
                data.put("fcmToken", fcmToken);
                fireEvent("didRefreshRegistrationToken", data);
            }
        });
    }

    @Kroll.method
    public void deleteToken() {
        FirebaseMessaging fm = FirebaseMessaging.getInstance();
        fm.deleteToken().addOnCompleteListener(task -> {
            KrollDict data = new KrollDict();
            if (task.isSuccessful()) {
                fcmToken = null;
            }
            data.put("success", task.isSuccessful());
            fireEvent("tokenRemoved", data);
        });
    }

    public void onTokenRefresh(String token) {
        try {
            if (hasListeners("didRefreshRegistrationToken")) {
                KrollDict data = new KrollDict();
                data.put("fcmToken", token);
                fireEvent("didRefreshRegistrationToken", data);
                fcmToken = token;
            }
        } catch (Exception e) {
            Log.e(LCAT, "Can't refresh token: " + e.getMessage());
        }
    }

    public boolean triggerDidReceiveMessage(String data, boolean inBackground) {
        if (!hasListeners("didReceiveMessage")) {
            return false;
        }

        KrollDict result = Utils.prepareEventResult(data, inBackground);
        if (result != null) {
            fireEvent("didReceiveMessage", result);
        }

        return true;
    }

    public void triggerDidReceiveMessageForRemoteMessage(RemoteMessage remoteMessage, boolean inBackground) {
        KrollDict data = Utils.prepareMessagePayload(remoteMessage);

        KrollDict message = new KrollDict();
        message.putAll(data);

        KrollDict result = new KrollDict();
        result.put("message", message);
        result.put("inBackground", inBackground);

        fireEvent("didReceiveMessage", result);
    }

    @Kroll.method
    public void createNotificationChannel(KrollDict options) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            return;
        }
        Log.d(LCAT, "createNotificationChannel " + options.toString());
        Context context = getApplicationContext();
        String sound = options.optString("sound", "default");
        String importance = options.optString("importance", sound.equals("silent") ? "low" : "default");
        String channelId = options.optString("channelId", "default");
        String channelName = options.optString("channelName", channelId);
        boolean vibration = options.optBoolean("vibrate", false);
        boolean lights = options.optBoolean("lights", false);
        boolean showBadge = options.optBoolean("showBadge", false);
        int importanceVal = NotificationManager.IMPORTANCE_DEFAULT;
        if (importance.equals("low")) {
            importanceVal = NotificationManager.IMPORTANCE_LOW;
        } else if (importance.equals("high")) {
            importanceVal = NotificationManager.IMPORTANCE_HIGH;
        }

        Uri soundUri = null;
        if (sound.equals("default") || sound.isEmpty()) {
            soundUri = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
        } else if (!sound.equals("silent")) {
            soundUri = Utils.getSoundUri(sound);
            Log.d(LCAT, "createNotificationChannel with sound " + sound + " at " + soundUri.toString());
        }

        NotificationChannel channel = new NotificationChannel(channelId, channelName, importanceVal);
        channel.enableVibration(vibration);
        channel.enableLights(lights);
        channel.setShowBadge(showBadge);
        if (soundUri != null) {
            AudioAttributes audioAttributes = new AudioAttributes.Builder()
                    .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                    .setUsage(AudioAttributes.USAGE_NOTIFICATION_RINGTONE)
                    .build();
            channel.setSound(soundUri, audioAttributes);
        }
        NotificationManager notificationManager =
                (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
        assert notificationManager != null;
        notificationManager.createNotificationChannel(channel);
    }

    @Kroll.method
    public void deleteNotificationChannel(String channelId) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            return;
        }
        Log.d(LCAT, "deleteNotificationChannel " + channelId);

        Context context = getApplicationContext();
        NotificationManager notificationManager =
                (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
        assert notificationManager != null;
        notificationManager.deleteNotificationChannel(channelId);
    }

    @Kroll.getProperty
    public String fcmToken() {
        if (fcmToken != null) {
            return fcmToken;
        } else {
            getToken();
            return null;
        }
    }

    // clang-format off
    @Kroll.setProperty
    @Kroll.method
    public void setNotificationChannel(Object channel)
    // clang-format on
    {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            return;
        }

        if (!(channel instanceof NotificationChannelProxy)) {
            return;
        }

        NotificationManager notificationManager =
                (NotificationManager) getApplicationContext().getSystemService(Context.NOTIFICATION_SERVICE);
        assert notificationManager != null;
        notificationManager.createNotificationChannel(((NotificationChannelProxy) channel).getNotificationChannel());
    }

    // clang-format off
    @Kroll.setProperty
    @Kroll.method
    public void setForceShowInForeground(final Boolean showInForeground)
    // clang-format on
    {
        SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());

        SharedPreferences.Editor editor = prefs.edit();
        editor.putBoolean(FORCE_SHOW_IN_FOREGROUND, showInForeground);
        editor.apply();
    }

    @Kroll.getProperty
    public Boolean forceShowInForeground() {
        SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
        return prefs.getBoolean(FORCE_SHOW_IN_FOREGROUND, false);
    }

    /**
     * Stores the payload of a tapped notification and tells the app about it.
     *
     * @return true when a listener actually received it, so the caller knows the
     *         Intent does not need to carry the payload as well.
     */
    public boolean triggerDidOpenNotification(boolean inBackground, String data) {
        notificationData = data;

        // PushHandlerActivity calls this the moment the user taps a notification,
        // before the app is brought to the front. When the runtime is already alive
        // the launcher Intent is not delivered a second time, so this event is the
        // only way the app gets to know about the tap. On a cold start the module
        // does not exist yet and parseBootIntent() reads the payload instead.
        if (!hasListeners("didOpenNotification")) {
            return false;
        }

        KrollDict result = Utils.prepareEventResult(data, inBackground);
        if (result != null) {
            fireEvent("didOpenNotification", result);
        }

        return true;
    }

    public void parseBootIntent() {
        try {
            Intent intent = getCurrentIntent();
            if (intent == null) {
                return;
            }

            // Boot intent is always invoked from killed state by tapping on the notification.
            String data = intent.getStringExtra("fcm_data");
            triggerDidReceiveMessage(data,true);
            clearLastData();
        } catch (Exception ex) {
            Log.e(LCAT, "parseBootIntent" + ex);
        }
    }

    public Boolean shouldNotifyOnPushTap() {
        return getProperties().getBoolean("notifyOnPushTap");
    }
}
